sudo: required
services:
  - docker

before_install:
  - docker build -t kuchbadakarenge/docker-react -f Dockerfile.dev .

script:
  - docker run kuchbadakarenge/docker-react npm run test -- --coverage
